### ISSUE TITLE
No playback on Cyanogenmod 13

### ISSUE THREAD

**Issue by postags** [gsantner/cherrymusic-android#5] opened 2016-10-28 21:16 UTC
Device: Samsung Galaxy S4
Android Version: Android 6.0.1 CM
App source: F-Droid
App version: 1.2.0

When I press play, the playlist selector jumps to the end of the playlist and no audio comes out. Pressing stop and play again has the same result. I opened the jPlayer inspector and found this error code:

status.media = {
last_error: 1477583062725
};

Here's the adb log:
[cherrylog.txt](https://github.com/gsantner/cherrymusic-android/files/559435/cherrylog.txt)

**Comment by gsantner** [comment] 2016-10-28 22:54
Seems to be an upstream bug in CM13 / the included chromium webview version. Or some kind of upstream bug in cherrymusic, because it can't handle some new features introduced in later chromium versions.

I didn't use cherrymusic since a long time, and installed it to find out what's causing your issue.

I got 2xCM13 devices, one with nightly 20160321 and one with  20161025. The issue is also happening on my device with latest updates.

I'm closing this now, because this is definetly an upstream issue.
BTW: I recommend to try some other music streamer now (and switch personally too), because it's pretty much dead, and still have big problems with **basics** like encoding. I am quite concered about  security too, nothing I would install on my production server.

**Closed by gsantner** 2016-10-28 22:54 UTC

**Comment by ladams00** [comment] 2016-11-03 17:38
gsanter, what other open source streaming platform can you recommend?

**Comment by gsantner** [comment] 2016-11-03 17:47
@ladams00 
<http://ampache.org/>
<https://github.com/Libresonic/libresonic>

**Comment by postags** [comment] 2016-11-03 19:49
I can second Libresonic. You currently need to build it yourself, but the instructions are easy to follow and it's the solution I was looking for in the first place (fully featured free version of Madsonic RIP).

This is also helpful for setting up Libresonic: https://wiki.archlinux.org/index.php/Subsonic


On November 3, 2016 10:47:53 AM PDT, Gregor Santner <notifications@github.com> wrote:
>@ladams00 
><http://ampache.org/>
><https://github.com/Libresonic/libresonic>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gsantner/cherrymusic-android/issues/5#issuecomment-258220424

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gsantner** [comment] 2016-11-03 20:22
@postags  I compiled it myself and used the debian package. Worked better than the other ways.
